### ISSUE TITLE
'Other Formula/Also Roll Other (save)' breaks damage rolls, can't roll damage or other formula

### ISSUE THREAD

**Issue by TogaParty** [unrealkakeman89/sw5e#364]
'Other Formula/Also Roll Other (save)' breaks damage rolls, can't roll damage or other formula

With these two settings applied (MIDI-QOL), damage doesn't roll automatically or manually from the chat card, nor can you roll Other Formula.

**Comment by TogaParty** [comment]
Some additional data.  This error occurs when you click "Other Formula" in the chat window with the console open:

entity.js:1345 Uncaught (in promise) TypeError: roll.toMessage is not a function
[Detected 1 package: system:sw5e]
    at Item5e.rollFormula (entity.js:1345:14)
    at Function._onChatCardAction (entity.js:1545:28)
